export interface Tool {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  path: string;
  keywords: string[];
}

export const tools: Tool[] = [
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON data",
    category: "Data",
    icon: "{ }",
    path: "/json-formatter",
    keywords: ["json", "format", "validate", "pretty print", "minify", "beautify"],
  },
  {
    id: "base64",
    name: "Base64 Encoder/Decoder",
    description: "Encode and decode Base64 strings",
    category: "Encoding",
    icon: "B64",
    path: "/base64",
    keywords: ["base64", "encode", "decode", "binary", "text"],
  },
  {
    id: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode and decode URL components",
    category: "Encoding",
    icon: "%20",
    path: "/url-encoder",
    keywords: ["url", "encode", "decode", "percent", "uri"],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes",
    category: "Crypto",
    icon: "#",
    path: "/hash-generator",
    keywords: ["hash", "md5", "sha", "sha256", "sha512", "checksum"],
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs (v4)",
    category: "Generator",
    icon: "ID",
    path: "/uuid-generator",
    keywords: ["uuid", "guid", "unique", "identifier", "random"],
  },
  {
    id: "timestamp-converter",
    name: "Unix Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates",
    category: "Date/Time",
    icon: "TS",
    path: "/timestamp-converter",
    keywords: ["unix", "timestamp", "epoch", "date", "time", "convert"],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate secure random passwords",
    category: "Security",
    icon: "***",
    path: "/password-generator",
    keywords: ["password", "generate", "random", "secure", "strong"],
  },
  {
    id: "qr-code",
    name: "QR Code Generator",
    description: "Generate QR codes from text or URLs",
    category: "Generator",
    icon: "QR",
    path: "/qr-code",
    keywords: ["qr", "qrcode", "barcode", "generate", "scan"],
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Tokens",
    category: "Security",
    icon: "JWT",
    path: "/jwt-decoder",
    keywords: ["jwt", "token", "decode", "json", "web", "auth"],
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions with live matching",
    category: "Text",
    icon: ".*",
    path: "/regex-tester",
    keywords: ["regex", "regexp", "regular", "expression", "test", "match"],
  },
  {
    id: "text-inspector",
    name: "Text Inspector",
    description: "Character count, byte size, Unicode code points",
    category: "Text",
    icon: "Aa",
    path: "/text-inspector",
    keywords: ["character", "count", "byte", "unicode", "encoding", "utf8", "length", "word"],
  },
  {
    id: "password-hasher",
    name: "Password Hasher",
    description: "Hash passwords with Argon2id, PBKDF2, and salt",
    category: "Crypto",
    icon: "🔑",
    path: "/password-hasher",
    keywords: ["argon2", "bcrypt", "pbkdf2", "hash", "salt", "password", "key derivation"],
  },
  {
    id: "test-data-generator",
    name: "Test Data Generator",
    description: "Generate dummy data for testing",
    category: "Generator",
    icon: "⚙",
    path: "/test-data-generator",
    keywords: ["test", "dummy", "fake", "mock", "data", "random", "lorem", "email", "name"],
  },
  {
    id: "diff-checker",
    name: "Diff Checker",
    description: "Compare two texts and highlight differences",
    category: "Text",
    icon: "±",
    path: "/diff-checker",
    keywords: ["diff", "compare", "difference", "text", "merge", "patch"],
  },
  {
    id: "halfwidth-fullwidth",
    name: "Halfwidth ↔ Fullwidth",
    description: "Convert between halfwidth and fullwidth characters",
    category: "Text",
    icon: "Ａa",
    path: "/halfwidth-fullwidth",
    keywords: ["halfwidth", "fullwidth", "zenkaku", "hankaku", "convert", "全角", "半角", "width"],
  },
  {
    id: "html-strip",
    name: "HTML Tag Stripper",
    description: "Remove HTML tags and extract plain text",
    category: "Text",
    icon: "</>",
    path: "/html-strip",
    keywords: ["html", "tag", "strip", "remove", "clean", "text", "extract"],
  },
  {
    id: "keyword-counter",
    name: "Keyword Counter",
    description: "Count keyword frequency and density",
    category: "Text",
    icon: "KW",
    path: "/keyword-counter",
    keywords: ["keyword", "count", "frequency", "density", "seo", "word", "occurrence"],
  },
  {
    id: "pdf-line-break-remover",
    name: "PDF Line Break Remover",
    description: "Remove unwanted line breaks from PDF-copied text",
    category: "Text",
    icon: "PDF",
    path: "/pdf-line-break-remover",
    keywords: ["pdf", "line break", "remove", "clean", "paragraph", "copy", "paste"],
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Preview and convert Markdown to HTML",
    category: "Converter",
    icon: "MD",
    path: "/markdown-preview",
    keywords: ["markdown", "html", "preview", "convert", "render", "md"],
  },
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Pick colors and generate palettes",
    category: "Design",
    icon: "🎨",
    path: "/color-picker",
    keywords: ["color", "picker", "palette", "hex", "rgb", "hsl", "css"],
  },
];

export const categories = [...new Set(tools.map((t) => t.category))];
